# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stuffdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 20, 19, 35, 7, 601827, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 20, 19, 35, 23, 326291, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
