# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffdb', '0002_auto_20160520_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='maker',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffdb.Role'),
        ),
        migrations.AddField(
            model_name='item',
            name='makers',
            field=models.ManyToManyField(to='stuffdb.Maker'),
        ),
    ]
